name: "Obfuscate js test application"
on: 
  push:

jobs:
  test-js-obfuscation:
    runs-on: ubuntu-latest

    steps:
      - name: Set current branch ref
        id: git_info
        run: |
          echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          echo "hash=$(git rev-parse --short \"$GITHUB_SHA\")" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.git_info.outputs.branch }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Low obfuscation test
        uses: KevinRohn/github-action-javascript-obfuscator@v1
        with:
          input_path: src
          output_path: src