name: Obfuscate JavaScript code
on: 
  push:


jobs:
  obfuscate_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from code branch
        uses: actions/checkout@v2

      # In this step you generally need to run some related command lines
      # of the JavaScript Obfuscator Tool to obfuscate the JavaScript code.
      # see 'https://github.com/javascript-obfuscator/javascript-obfuscator#cli-usage'
      - name: Obfuscate JavaScript code
        working-directory: js
        run: javascript-obfuscator common.js --output common.js
        